# Generated by Django 5.1.3 on 2026-02-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_about_alter_blog_id_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_description',
            field=models.TextField(max_length=200),
        ),
    ]
