# Generated by Django 5.1.3 on 2026-02-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_about_about_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_header', models.CharField(max_length=50)),
                ('link_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
